### ISSUE TITLE
签到借口是不是改变了？

### ISSUE THREAD

**Issue by ySirius** [chesterchenn/jd-bot#1]

**Comment by chesterchenn** [comment]
没有吧，我这边还是正常

**Comment by chesterchenn** [comment]
@ySirius 没有吧，我这边刚运行一下是正常的

**Comment by ySirius** [comment]
我用的另一个库 显示API请求失败 不知道咋搞的

**Comment by ySirius** [comment]
> @ySirius 没有吧，我这边刚运行一下是正常的

你能点进去具体看一下吗运行过程里头吗，运行没有问题，里头显示API调用错误

**Comment by chesterchenn** [comment]
> 
> 
> 我用的另一个库 显示API请求失败 不知道咋搞的

你用的是哪一个库？

**Comment by ySirius** [comment]
我用的 wuzhi01 的库，好像是确实改接口了

**Comment by chesterchenn** [comment]
> 
> 
> 我用的 wuzhi01 的库，好像是确实改接口了

看了一下，NobyDa 提供了两个接口，一个是 cdn.jsdelivr.net，一个是 raw.githubusercontent.com。你代码中默认使用后者，请求后者会失败，修改成前者就可以了。

**Comment by ySirius** [comment]
> > 我用的 wuzhi01 的库，好像是确实改接口了
> 
> 看了一下，NobyDa 提供了两个接口，一个是 cdn.jsdelivr.net，一个是 raw.githubusercontent.com。你代码中默认使用后者，请求后者会失败，修改成前者就可以了。

好的 我一会试一下，谢谢回复
